project:
  input_dir: diaad_data/input
  output_dir: diaad_data/output
  random_seed: 99
  reliability_fraction: 0.2
  shuffle_samples: true
  strip_clan: true
  prefer_correction: true
  lowercase: true
  exclude_participants: []
  auto_tabularize: false
  num_bins: 4
  num_coders: 0
  stimulus_field: ''
  automate_powers: true
  metadata_fields: {}
advanced:
  sample_id_field: sample_id
  utterance_id_field: utterance_id
  reliability_tag: _reliability
  reliability_dirname: reliability
  cu_paradigms: []
  cu_samples_file: cu_coding_by_sample_long.xlsx
  cu_utts_file: cu_coding_by_utterance.xlsx
  word_count_file: word_counting.xlsx
  word_count_field: word_count
  wc_samples_file: word_counting_by_sample.xlsx
  speaking_time_file: speaking_times.xlsx
  speaking_time_field: speaking_time
  powers_coding_file: powers_coding.xlsx
  powers_reliability_file: powers_reliability_coding.xlsx
  target_vocabulary_resource_path: ''
  auto_blind: false
  blind_cols:
  - sample_id
  metadata_source: transcript_tables
  codebook_filename: ''
